# fly.toml app configuration file generated for service-template-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'service-template-backend'
primary_region = 'iad'

[build]
  dockerfile = 'backend/Dockerfile'

[env]
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/health'

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'

[[statics]]
  guest_path = '/app/static'
  url_prefix = '/static'