#!/bin/bash

# Service Template Local Development Environment Setup
# This script extracts Supabase keys and creates .env.local

set -e

echo "🚀 Setting up local development environment..."

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo "❌ Supabase CLI not found. Please install it first:"
    echo "   npm install -g supabase"
    exit 1
fi

# Check if Supabase is running
if ! supabase status &> /dev/null; then
    echo "⚠️  Supabase is not running. Starting it now..."
    supabase start
fi

echo "📡 Extracting Supabase configuration..."

# Get Supabase status and extract keys
SUPABASE_STATUS=$(supabase status)

# Extract API URL (should be http://127.0.0.1:54321)
API_URL=$(echo "$SUPABASE_STATUS" | grep "API URL" | awk '{print $3}')

# Extract anon key
ANON_KEY=$(echo "$SUPABASE_STATUS" | grep "anon key" | awk '{print $3}')

# Extract service role key
SERVICE_KEY=$(echo "$SUPABASE_STATUS" | grep "service_role key" | awk '{print $3}')

# Validate that we got the keys
if [[ -z "$API_URL" || -z "$ANON_KEY" || -z "$SERVICE_KEY" ]]; then
    echo "❌ Failed to extract Supabase keys. Please check 'supabase status' output."
    echo "Expected format:"
    echo "  API URL: http://127.0.0.1:54321"
    echo "  anon key: ey..."
    echo "  service_role key: ey..."
    exit 1
fi

echo "✅ Successfully extracted Supabase keys"

# Create .env.local from template
echo "📝 Creating .env.local file..."

cat > .env.local << EOF
# =================================
# Service Template Local Development Environment
# =================================
# Auto-generated by scripts/setup-env.sh
# Generated on: $(date)

# Supabase Configuration (Local)
NEXT_PUBLIC_SUPABASE_URL=http://host.docker.internal:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_URL=http://host.docker.internal:54321
SUPABASE_SERVICE_KEY=$SERVICE_KEY

# Application Configuration
APP_NAME=Service Template
APP_URL=http://localhost:3000
API_URL=http://localhost:8000

# Environment Settings
NODE_ENV=development
ENVIRONMENT=development
PYTHONPATH=/app
PYTHONUNBUFFERED=1

# Frontend Development Settings
NEXT_TELEMETRY_DISABLED=1
WATCHPACK_POLLING=true

# External API Keys (Add your service integrations here)
# OPENAI_API_KEY=sk-local-dev-mock-key-replace-for-real-testing
# STRIPE_SECRET_KEY=your-stripe-key-here
# SENDGRID_API_KEY=your-sendgrid-key-here
EOF

echo "✅ Created .env.local with Supabase keys"

echo ""
echo "🎉 Setup complete! Your local development environment is ready."
echo ""
echo "Next steps:"
echo "  1. Run 'mise dev' to start all services"
echo "  2. Visit http://localhost:3000 for the frontend"
echo "  3. Visit http://localhost:8000 for the backend API"
echo "  4. Visit http://localhost:54323 for Supabase Studio"
echo ""
echo "To reset everything: 'mise reset'"